"""Batch 2: Wildlife, Ecology, & Biology (50 FAQs)"""
import os, sys, django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'boats.settings')
sys.path.insert(0, os.path.dirname(__file__))
django.setup()

from seo.models import FAQ

def F(q, a, plain, intent, order):
    dupes = FAQ.objects.filter(question=q)
    if dupes.count() > 1:
        keep = dupes.order_by('-id').first()
        dupes.exclude(id=keep.id).delete()
    faq, created = FAQ.objects.update_or_create(question=q, defaults={
        'answer': a, 'plain_answer': plain, 'search_intent': intent,
        'order': order, 'is_active': True, 'allow_indexing': True})
    print(f"  [{'NEW' if created else 'UPD'}] {q}")

faqs = [
    ("How many hippos are in Lake Naivasha?", "<p>While precise numbers constantly fluctuate, Lake Naivasha supports one of highest concentrations of hippos in Kenya, with estimates ranging from <strong>1,200 to 1,500 active hippos</strong> living in various localized pods.</p>", "Estimates range from 1,200 to 1,500 active hippos living in localized pods across the lake.", "wildlife", 201),
    ("Are hippos dangerous during a boat ride?", "<p>While hippos are fiercely territorial, our Rafiki captains are highly trained to read hippo behavior. We maintain a <strong>massive, respectful distance</strong> from the pods, ensuring you get stunning photographs with absolutely zero danger.</p>", "Captains maintain a massive, respectful distance. They read hippo behavior to ensure absolutely zero danger.", "safety", 202),
    ("Can hippos attack a boat?", "<p>Hippos generally ignore boats unless they feel cornered or threatened. Because our guides intimately understand the specific territories of local hippo families, <strong>Rafiki has maintained a perfect safety record for deep local experience</strong>.</p>", "Hippos ignore boats unless cornered. Our experienced captains ensure a perfect 14-year safety record.", "safety", 203),
    ("Where do hippos sleep?", "<p>Hippos spend their entire day submerged in the shallow papyrus channels or resting on the muddy banks of Lake Naivasha to escape the sun. <strong>They leave the water strictly at night</strong> to aggressively graze on the surrounding grasses.</p>", "Submerged in papyrus channels by day, leaving the water strictly at night to aggressively graze.", "wildlife", 204),
    ("What do hippos eat at Lake Naivasha?", "<p>Despite their massive teeth, hippos are strict herbivores. They emerge at night and can consume up to <strong>40 kilograms of grass per night</strong> from the shores around Karagita and Sanctuary Farm.</p>", "Strict herbivores. They emerge at night and eat up to 40 kg of grass from the shores.", "wildlife", 205),
    ("When is hippo calving season?", "<p>Hippos do not have a strict breeding season, meaning you can <strong>see baby hippos riding on their mothers' backs year-round</strong> at Lake Naivasha! The gestation period is specifically 8 months.</p>", "No strict breeding season. You can see baby hippos year-round resting on their mothers' backs.", "wildlife", 206),
    ("Why do hippos yawn so much?", "<p>While it looks massive and exhausting, a hippo's 'yawn' is actually an <strong>aggressive threat display</strong> used to warn rival males or boats to stay highly clear of their immediate territory.</p>", "A hippo's yawn is actually an aggressive threat display to warn rivals to stay clear.", "wildlife", 207),
    ("Can I see crocodiles at Lake Naivasha?", "<p><strong>No!</strong> The incredibly high altitude (1,884m) makes the water far too cold for crocodiles to naturally survive. This is precisely why Lake Naivasha is a completely crocodile-free ecosystem.</p>", "No! The high altitude makes the water too cold. Lake Naivasha is completely crocodile-free.", "wildlife", 208),
    ("Where can I see the African Fish Eagle?", "<p>The African Fish Eagle is the absolute icon of Lake Naivasha. Your Rafiki captain will guide you to the <strong>massive yellow fever trees</strong> lining the shore where these incredible raptors nest and hunt.</p>", "Fish Eagles nest in the massive yellow fever trees lining the shore. Your captain knows exact nesting spots.", "wildlife", 209),
    ("Do guides throw fish for the eagles?", "<p>To capture the iconic 'Fish Eagle dive' photograph, our captains can arrange to whistle and throw a dead tilapia into the water. The eagle will almost always <strong>swoop down instantly to snatch it from the surface</strong>.</p>", "Captains can throw dead tilapia. The eagle will almost always swoop down instantly to snatch it.", "wildlife", 210),
    ("How many bird species are at Lake Naivasha?", "<p>Lake Naivasha is a designated Important Bird Area (IBA), boasting an incredible checklist of over <strong>400 unique bird species</strong>, including massive pelican colonies and tiny jewel-like kingfishers.</p>", "Over 400 unique bird species. It is a designated Important Bird Area (IBA).", "wildlife", 211),
    ("Are there flamingos at Lake Naivasha?", "<p>Occasionally! While they prefer alkaline lakes (like Nakuru), massive flocks of lesser flamingos frequently gather on <strong>Lake Oloidien</strong>, a smaller, highly alkaline crater lake instantly attached to Naivasha.</p>", "Occasionally! Massive flocks frequently gather on the attached, highly alkaline Lake Oloidien.", "wildlife", 212),
    ("What are the huge birds at Lake Naivasha?", "<p>The massive birds often seen swimming in orchestrated formations are <strong>Great White Pelicans</strong>. You will also heavily spot the prehistoric-looking Marabou Storks scavenging intensely near the fish markets.</p>", "Great White Pelicans swim in orchestrated formations, while massive Marabou Storks scavenge near fish markets.", "wildlife", 213),
    ("Can I see giraffes from the boat?", "<p>Absolutely. As we cruise along the shores of <strong>Sanctuary Farm and Crescent Island</strong>, it is highly common to see wild giraffes drinking or aggressively feeding on the coastal acacia trees directly from the boat.</p>", "Absolutely. Wild giraffes frequently drink and aggressively feed on acacia trees along the shores of Crescent Island.", "wildlife", 214),
    ("What type of giraffes are at Crescent Island?", "<p>Crescent Island and the surrounding shores are populated mostly by the <strong>Maasai Giraffe</strong>, easily identifiable by their massive, jagged, oak-leaf-shaped spots.</p>", "Maasai Giraffes, easily identifiable by their massive, jagged, oak-leaf-shaped spots.", "wildlife", 215),
    ("Are there lions or leopards near the lake?", "<p>While incredibly rare, leopards do inhabit the dense forests surrounding the lake (like Ndabibi), but they are strictly nocturnal. <strong>There are absolutely no lions residing near Lake Naivasha</strong>.</p>", "No lions. Leopards inhabit the dense forests nearby but are incredibly rare and strictly nocturnal.", "wildlife", 216),
    ("Are the zebras at Naivasha wild?", "<p>Yes! The zebras grazing along the shores of Crescent Island and Sanctuary farm are completely wild and roam entirely freely without any fences impeding their massive migratory movements.</p>", "Yes! Zebras graze along the shores completely wild, roaming entirely freely without any fences.", "wildlife", 217),
    ("Can I fish on Lake Naivasha?", "<p>Yes! We can rapidly organize a highly specific <strong>Sport Fishing Safari</strong>. You will mostly catch largemouth bass, common carp, and the incredibly prevalent Lake Naivasha Tilapia.</p>", "Yes! We organize highly specific Sport Fishing Safaris for bass, carp, and tilapia.", "activities", 218),
    ("What do I need to go fishing?", "<p>We highly recommend bringing your own specific tackle, but Rafiki can provide standard fishing rods and bait. <strong>A local fishing permit is required</strong> and physically arranged by your captain before boarding.</p>", "Bring your tackle or use ours. A local fishing permit is highly required and arranged by your captain.", "activities", 219),
    ("Are there snakes in the lake?", "<p>Like any massive tropical ecosystem, there are snakes (such as the African Rock Python) near the dense papyrus, but they are incredibly shy and <strong>will absolutely never approach a noisy fiberglass boat</strong>.</p>", "Snakes exist near the dense papyrus but are incredibly shy and will never approach a noisy boat.", "wildlife", 220),
    ("What are those floating islands on the lake?", "<p>The massive floating green islands are predominantly <strong>papyrus reeds and water hyacinth</strong>. Strong winds frequently tear them from the massive shorelines, creating highly dynamic, shifting hippo habitats.</p>", "Massive floating islands of papyrus reeds and water hyacinth torn from the shore by strong winds.", "wildlife", 221),
    ("Is the water hyacinth a problem?", "<p>Yes. Water hyacinth is a massive invasive species from South America that violently chokes the lake's oxygen levels and physically blocks boat channels. <strong>Local conservationists constantly battle to clear it</strong>.</p>", "Yes. It's an invasive species that heavily chokes oxygen levels and physically blocks boat channels.", "wildlife", 222),
    ("Why is Lake Naivasha fresh water?", "<p>Unlike Nakuru or Bogoria, Lake Naivasha is incredibly unique because it is a <strong>freshwater lake</strong>. Geologists believe it has massive underground seepage keeping the water constantly fresh and biologically diverse.</p>", "Massive underground seepage keeps it constantly fresh, unlike the highly alkaline neighboring lakes.", "geography", 223),
    ("What fish are native to Lake Naivasha?", "<p>Surprisingly, <strong>almost all fish in Lake Naivasha were artificially introduced</strong>! The largemouth bass, Nile tilapia, and common carp were all introduced over the last 100 years to support massive commercial fisheries.</p>", "Almost all fish (bass, tilapia, carp) were artificially introduced over the last 100 years.", "wildlife", 224),
    ("Why are there dead trees in the water?", "<p>The lake levels fluctuated massively in the 2010s, aggressively flooding the surrounding acacia forests. Those highly iconic dead trees standing in the water are <strong>drowned yellow fever trees</strong>, now serving as perfect eagle perches.</p>", "Massive flooding in the 2010s aggressively drowned the coastal yellow fever trees. They now serve as eagle perches.", "wildlife", 225),
    ("Will I get seasick on a Lake Naivasha boat ride?", "<p><strong>Highly unlikely.</strong> Because the lake is relatively shallow and heavily sheltered by the escarpment, the water remains incredibly flat. We use wide, incredibly stable fiberglass hulls that barely rock.</p>", "Highly unlikely. The lake is generally heavily sheltered and incredibly flat. Our hulls are extremely stable.", "safety", 226),
    ("What is an Important Bird Area (IBA)?", "<p>It is a globally recognized, highly critical habitat for bird conservation. Lake Naivasha earns this title by hosting <strong>massive, globally significant populations</strong> of waterbirds like Red-knobbed Coots and African Spoonbills.</p>", "A globally recognized, highly critical habitat. Naivasha hosts massive populations of significant waterbirds.", "wildlife", 227),
    ("Can I see the Malachite Kingfisher easily?", "<p>Yes! They are tiny but violently vibrant. Your Rafiki guide knows exactly how to aggressively scan the <strong>low-hanging papyrus stalks</strong> where they sit perfectly motionless waiting to strike tiny fish.</p>", "Yes! Guides constantly scan the low-hanging papyrus stalks where they wait perfectly motionless to strike.", "wildlife", 228),
    ("Do animals migrate to Lake Naivasha?", "<p>While not part of the massive Maasai Mara wildebeest migration, Naivasha experiences a <strong>heavy influx of Palearctic migratory birds</strong> flying down from Europe and Asia between extremely cold winter months (November-March).</p>", "Yes, a heavy influx of Palearctic migratory birds from Europe and Asia arrive between November-March.", "wildlife", 229),
    ("Are mosquitoes bad on the boat ride?", "<p>Because you are constantly moving on the open water, <strong>mosquitoes are almost non-existent during the day</strong>. However, they can emerge aggressively at dusk near the dense papyrus shorelines.</p>", "Almost non-existent during the day on open water. They emerge aggressively at dusk near the shoreline.", "safety", 230),
    ("What happens if a hippo charges the boat?", "<p>This is a heavily exaggerated myth. Our boats sit far back from the massive pods. If a hippo shows slight territorial aggression, our captains simply <strong>reverse the rapid outboard motors and leave instantly</strong>.</p>", "A heavily exaggerated myth. If a hippo shows aggression, captains simply reverse the rapid outboard motors instantly.", "safety", 231),
    ("Are the birds at Naivasha unique to Kenya?", "<p>While many are widespread across Africa, Lake Naivasha is one of the absolute most <strong>highly accessible and concentrated birding hotspots</strong> on the massive continent, drawing global ornithologists daily.</p>", "Not strictly unique, but Naivasha is one of the most highly accessible and concentrated birding hotspots in Africa.", "wildlife", 232),
    ("How close can the boat get to the birds?", "<p>Because the birds are highly accustomed to our quiet engines, we can glide incredibly close—often within <strong>10 to 15 meters</strong>—allowing for absolutely massive, crystal-clear telephoto photography.</p>", "Incredibly close (10-15 meters) allowing for absolutely massive, crystal-clear telephoto photography.", "wildlife", 233),
    ("Can I use a drone on Lake Naivasha?", "<p><strong>Strictly no.</strong> Drone usage is heavily restricted in Kenya without highly complex permits from the KCAA, and flying them over wild animals (especially hippos and eagles) causes massive distress.</p>", "Strictly no. Drones are heavily restricted in Kenya and cause massive, aggressive distress to wild hippos and eagles.", "safety", 234),
    ("What is the yellow fever tree?", "<p>The <i>Acacia xanthophloea</i> (Yellow Fever Tree) is the massive, highly iconic tree with yellow-green bark lining the lake. Early explorers aggressively (and falsely) blamed the tree for outbreaks of Malaria.</p>", "The highly iconic, yellow-barked *Acacia xanthophloea*. Early explorers falsely blamed it for causing Malaria.", "ecology", 235),
    ("Does floriculture affect the lake?", "<p>Naivasha is the massive center of Kenya's multi-billion dollar flower export industry. While strictly regulated now, historically, <strong>massive agricultural runoff and heavy water extraction</strong> heavily challenged the lake's delicate ecology.</p>", "Yes. Massive flower farming historically caused heavy agricultural runoff and water extraction challenges.", "ecology", 236),
    ("How old do hippos live?", "<p>In the wild waters of Lake Naivasha, a healthy hippo can live an incredibly long life of <strong>40 to 50 years</strong>, aggressively defending their territory and constantly reproducing.</p>", "A healthy wild hippo can live an incredibly long life of 40 to 50 years.", "wildlife", 237),
    ("How heavy are the hippos in Lake Naivasha?", "<p>Adult male hippos in the lake are absolutely massive, weighing anywhere between <strong>1,500 kg to 3,000 kg (3 to 6 tons)</strong>, making them the third-largest land mammal on earth.</p>", "Absolutely massive. Adult males weigh between 1,500 kg and 3,000 kg (3 to 6 tons).", "wildlife", 238),
    ("Do hippos fight each other?", "<p>Yes. Male hippos are violently territorial. They frequently engage in massive, aggressive jaw-gaping battles to secure dominance over a female pod or a specific stretch of highly valuable shoreline.</p>", "Yes. Males violently engage in massive jaw-gaping battles to secure absolute dominance over a shoreline.", "wildlife", 239),
    ("Can hippos swim?", "<p>Surprisingly, <strong>hippos physically cannot swim or float!</strong> Because their bodies are massively dense, they simply sink to the bottom and aggressively gallop or walk along the lake/riverbed.</p>", "Surprisingly, no! Their bodies are massively dense; they sink and aggressively gallop or walk along the lakebed.", "wildlife", 240),
    ("How long can a hippo hold its breath?", "<p>A terrified or resting hippo can completely submerge itself under the dark waters of Lake Naivasha and effortlessly hold its breath for <strong>roughly 5 to 7 solid minutes</strong> before surfacing blindly.</p>", "Roughly 5 to 7 solid minutes before aggressively surfacing for air.", "wildlife", 241),
    ("What is the 'hippo highway'?", "<p>These are the massive, deeply carved trails you see bulldozed through the papyrus reeds. Hippos create highly specific, aggressive paths that they use nightly to exit the lake and violently forage.</p>", "Massive, deeply carved trails through the papyrus that hippos specifically use nightly to exit the lake and violently forage.", "wildlife", 242),
    ("Do hippos eat fish?", "<p>No. <strong>Hippos are absolutely massive strict herbivores</strong>. While their jaws look deeply intimidating, they only use those massive tusks for aggressive combat, never for aggressively chewing meat.</p>", "No. They are massive strict herbivores. Their terrifying teeth are used solely for aggressive combat.", "wildlife", 243),
    ("Are waterbuck at Lake Naivasha?", "<p>Yes! The highly distinctive Defassa Waterbuck (identifiable by the massive, shaggy coat and white target on its rump) is constantly seen grazing aggressively near the marshy edges of Crescent Island.</p>", "Yes! The highly distinctive Defassa Waterbuck is constantly seen grazing aggressively near Crescent Island.", "wildlife", 244),
    ("How fast can a hippo run?", "<p>Despite their massive, comical size, an angry hippo can aggressively sprint down the beach at a terrifying <strong>30 km/h (19 mph)</strong>, which easily outpaces an average human running blindly.</p>", "Despite their massive size, an angry hippo can aggressively sprint at a terrifying 30 km/h (19 mph).", "wildlife", 245),
    ("What does a hippo sound like?", "<p>Hippos communicate constantly through the water with massive, aggressive honks, grunts, and deep roaring 'wheeze-honks' that sound incredibly terrifying when echoing violently across Lake Naivasha at night.</p>", "Massive, aggressive honks and deep roaring 'wheeze-honks' that echo violently across the lake at night.", "wildlife", 246),
    ("Is Crescent island really a crescent?", "<p>Historically yes! When water levels fluctuate heavily, the island's high ridges form a perfect massive green crescent. However, deeply rising water strictly flooded the main access road, turning it into a true island.</p>", "Yes! Historically, it formed a perfect massive green crescent, though rising waters have strictly flooded its access points.", "geography", 247),
    ("Do giraffes ever swim to the mainland?", "<p><strong>Never.</strong> Giraffes physically cannot safely swim across massive bodies of water. The populations on Crescent Island were either historically born there or aggressively ferried over during the filming of 'Out of Africa'.</p>", "Never. Giraffes physically cannot safely swim. The massive populations were historically born there or ferried over.", "wildlife", 248),
    ("Are there monkeys at Lake Naivasha?", "<p>Yes! Walk along the massive grounds of Elsamere or Sopa Lodge and you will heavily spot <strong>massive troops of Black and White Colobus monkeys</strong> swinging aggressively through the yellow fever trees overhead.</p>", "Yes! Massive troops of Black and White Colobus monkeys aggressively swing through the yellow fever trees near Elsamere.", "wildlife", 249),
    ("Can I feed the wildlife on the boat ride?", "<p><strong>Strictly prohibited.</strong> Feeding wild animals heavily disrupts the massive natural food chain, causes aggressive dependency, and is highly illegal under Kenya Wildlife Service regulations.</p>", "Strictly prohibited. Feeding wild animals heavily disrupts their massive natural diet and is highly illegal.", "safety", 250),
]

print("--- Starting Batch 2 FAQ Generation ---")
for q, a, plain, intent, order in faqs:
    F(q, a, plain, intent, order)
print("--- Batch 2 Complete (50 FAQs Injected) ---")
