"""Batch 1: Logistics, Booking & Transport (50 FAQs)"""
import os, sys, django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'boats.settings')
sys.path.insert(0, os.path.dirname(__file__))
django.setup()

from seo.models import FAQ

def F(q, a, plain, intent, order):
    dupes = FAQ.objects.filter(question=q)
    if dupes.count() > 1:
        keep = dupes.order_by('-id').first()
        dupes.exclude(id=keep.id).delete()
    faq, created = FAQ.objects.update_or_create(question=q, defaults={
        'answer': a, 'plain_answer': plain, 'search_intent': intent,
        'order': order, 'is_active': True, 'allow_indexing': True})
    print(f"  [{'NEW' if created else 'UPD'}] {q}")

faqs = [
    ("How long is the bus ride from Nairobi to Lake Naivasha?", "<p>The bus or matatu ride from Nairobi to Naivasha takes approximately <strong>1.5 to 2 hours</strong> depending on traffic along the escarpment. It is a highly scenic route down the Great Rift Valley.</p>", "1.5 to 2 hours depending on Escarpment traffic.", "transport", 101),
    ("How much is a matatu from Nairobi to Naivasha?", "<p>A direct matatu from Nairobi's central business district (CBD) to Naivasha town costs between <strong>KES 300 and KES 500</strong> per person one way. From Naivasha town, you take another matatu to Karagita (Lake Naivasha Beach) for KES 50-100.</p>", "Between KES 300 and KES 500. Plus an extra KES 50-100 to reach Karagita Beach.", "pricing", 102),
    ("Where do I board matatus to Naivasha in Nairobi?", "<p>You can board matatus heading to Naivasha at the <strong>Nyamakima stage or Mololine stage</strong> in downtown Nairobi CBD. They fill up quickly and leave regularly throughout the day.</p>", "At Nyamakima stage or Mololine stage in Nairobi CBD.", "transport", 103),
    ("Can I take the SGR train to Lake Naivasha?", "<p>Yes! You can take the <strong>Madaraka Express (SGR)</strong> from the Nairobi Terminus (Syokimau) to the Suswa or Mai Mahiu stations. However, driving or taking a matatu is often faster as the stations are quite far from the lake itself.</p>", "Yes, via the Madaraka Express to Suswa or Mai Mahiu stations. But driving is usually faster.", "transport", 104),
    ("How much is the entrance fee to Lake Naivasha?", "<p>There is <strong>no entrance fee</strong> to access Lake Naivasha via Public Beach (Karagita). Unlike national parks, the lake is open public water. You only pay for your actual boat ride or activities.</p>", "No entrance fee! The lake is free to access via public beaches. You only pay for your boat ride.", "pricing", 105),
    ("Are there group discounts for Lake Naivasha boat rides?", "<p>Yes, Rafiki Boat Rides offers significant <strong>group discounts for parties of 10 or more</strong>. We can utilize our larger vessels or arrange a flotilla of boats depending on your group size.</p>", "Yes, we offer group discounts for parties of 10 or more passengers.", "pricing", 106),
    ("Do you offer student or school trip rates?", "<p>Absolutely. We provide heavily subsidized <strong>rates for educational tours and school groups</strong>. Our captains provide educational commentary on the Rift Valley ecosystem, hippos, and birdlife.</p>", "Yes, we offer heavily subsidized educational rates for schools and students.", "pricing", 107),
    ("Can I pay for my boat ride with M-Pesa?", "<p>Yes, Rafiki is fully integrated with <strong>M-Pesa (Lipa Na M-Pesa tracking)</strong>. You can simply send the money directly to our business till number before boarding your boat.</p>", "Yes, we are fully integrated with M-Pesa till numbers for seamless payments.", "pricing", 108),
    ("Do you accept US Dollars or Euros?", "<p>Yes. We accept cash payments in <strong>Kenyan Shillings (KES), US Dollars (USD), and Euros (EUR)</strong> at the current daily exchange rate.</p>", "We accept KES, USD, and EUR cash at current daily exchange rates.", "pricing", 109),
    ("Can I use a credit card at the lake?", "<p>Currently, we do not have a credit card swiping machine at the beach. We heavily recommend using <strong>M-Pesa, cash, or an international wire transfer</strong> in advance for large group bookings.</p>", "No credit card swipers at the beach. We recommend M-Pesa, cash, or bank transfers.", "pricing", 110),
    ("Do I need to tip the boat captain?", "<p><strong>Tipping is highly appreciated but not mandatory</strong>. Our captains work hard to get you the closest, safest wildlife sightings. A standard tip is between KES 200 and KES 1000 per group.</p>", "Tipping is appreciated but not mandatory. Standard tip is KES 200 - KES 1000 per group.", "guidance", 111),
    ("Is there parking available at Lake Naivasha Beach?", "<p>Yes! There is a <strong>massive, secure parking lot</strong> at Public Beach (Karagita). It is heavily monitored by local authorities and safe for both personal cars and large tour buses.</p>", "Yes, massive and secure parking at Public Beach for cars and large tour buses.", "logistics", 112),
    ("How much does parking cost at Lake Naivasha?", "<p>Parking at Public Beach is usually subject to a highly nominal county fee, typically around <strong>KES 100 to KES 200</strong> per vehicle for the entire day.</p>", "Nominal county fee, usually KES 100 to 200 per vehicle per day.", "pricing", 113),
    ("Is the road to Lake Naivasha paved?", "<p>Yes, the main Nairobi-Nakuru highway (A104) is fully paved. The Moi South Lake Road leading to our boat launch at Karagita is also <strong>fully paved and accessible by any 2WD vehicle</strong>.</p>", "Yes, both the A104 highway and the Moi South Lake Road are fully paved and 2WD friendly.", "logistics", 114),
    ("How do I book a boat ride in advance?", "<p>The easiest way to book is to send a direct <strong>WhatsApp message to +254 701 215 295</strong>. Let us know your date, time, and group size, and we will lock in your captain immediately.</p>", "WhatsApp +254 701 215 295 with your date, time, and group size to instantly lock in a captain.", "booking", 115),
    ("What are the operating hours for Rafiki Boat Rides?", "<p>We operate from exactly <strong>6:30 AM (Sunrise) until 6:30 PM (Sunset)</strong> every single day of the year, including all major holidays and weekends.</p>", "6:30 AM to 6:30 PM, every single day including all public holidays.", "logistics", 116),
    ("Can I show up without a booking?", "<p>Yes! Rafiki operates a fleet of highly dynamic vessels. Walk-ins at Public Beach, Karagita are welcome, though <strong>pre-booking is highly recommended on massive holiday weekends</strong> (like Easter or Christmas) to avoid waiting.</p>", "Walk-ins are welcome, but pre-booking is recommended on major holidays to secure a boat without waiting.", "booking", 117),
    ("How long does a standard boat ride take?", "<p>The standard hippo and bird-watching safari lasts exactly <strong>1 hour</strong>. However, you can book customized 2, 3, or even 5-hour extended photography safaris upon request.</p>", "Standard rides last exactly 1 hour. Extended custom rides are available upon request.", "logistics", 118),
    ("How does pricing work for private boat rides?", "<p>Private charters (where you have the <strong>entire boat exclusively for your group</strong>) are priced by the hour rather than per person. WhatsApp us for the exact hourly rate for our 7-seater or 12-seater private vessels.</p>", "Private rides are priced per hour, per boat, rather than per person. Ensures exclusivity.", "pricing", 119),
    ("What happens if we arrive late for our booking?", "<p>Since we operate on standard Kenyan time, we offer massive flexibility. Your captain will simply hold your boat. However, if you are doing a Sunset Cruise, <strong>arriving past 5:30 PM means you will miss the sun dropping behind the escarpment</strong>.</p>", "We are flexible, but arriving late for a sunset cruise means you will miss the actual sunset.", "logistics", 120),
    ("Do I need a 4x4 vehicle to reach Rafiki Boat Rides?", "<p><strong>Absolutely not</strong>. The entire route from Nairobi to the Karagita Public Beach launch point is fully tarmacked. A standard sedans or tiny hatchback will easily make the trip.</p>", "No 4x4 needed. The entire route from Nairobi is completely tarmacked.", "logistics", 121),
    ("Is there an airport near Lake Naivasha?", "<p>The closest major international airport is <strong>Jomo Kenyatta International Airport (JKIA)</strong> in Nairobi. However, Naivasha does have the highly active 'Loldia Airstrip' for chartered bush flights directly onto the lake.</p>", "The closest major airport is JKIA in Nairobi. Chartered flights can land at the local Loldia Airstrip.", "transport", 122),
    ("Can I get an Uber from Nairobi to Naivasha?", "<p>Yes, incredibly, an Uber driver will take you from Nairobi to Naivasha (approx KES 5,000 - KES 8,000). However, <strong>you will likely have trouble finding an Uber to take you back</strong> to Nairobi. We recommend a private taxi instead.</p>", "Yes, but finding a return Uber from Naivasha is nearly impossible. Use a private taxi.", "transport", 123),
    ("Do you offer airport transfer services?", "<p>Rafiki partners with several highly trusted local taxi and tour operators. We can **arrange a private transfer** for you from Jomo Kenyatta International Airport directly to your boat.</p>", "Yes, we partner with trusted local operators to arrange direct airport transfers.", "transport", 124),
    ("Can I leave my luggage on the boat?", "<p>We do not recommend bringing heavy suit cases on the fiberglass boats. However, you can safely <strong>leave your luggage in your locked car at the secure Karagita beach parking lot</strong>, or at your hotel's reception before boarding.</p>", "Leave heavy luggage in your locked car at the secure parking lot, or at your hotel reception.", "logistics", 125),
    ("Where is Rafiki located on Lake Naivasha?", "<p>Rafiki operates out of the massive <strong>Public Beach at Karagita</strong>, located along the Moi South Lake Road. Look for the massive concentration of highly colorful fiberglass boats.</p>", "We operate out of the Public Beach at Karagita on Moi South Lake Road.", "logistics", 126),
    ("Are your boats wheelchair accessible?", "<p>While the beaches can be slightly sandy, our crew is highly trained in <strong>physically lifting and assisting disabled or elderly guests</strong> safely into and out of our massive fiberglass vessels.</p>", "Beaches are sandy, but our crew is trained to safely assist and lift disabled guests into the boats.", "logistics", 127),
    ("Do you operate on Christmas Day?", "<p><strong>Yes! Every single holiday.</strong> Christmas, Easter, New Year's Day, and all Kenyan National Holidays are actually our busiest, most vibrant days on the lake.</p>", "Yes! We operate on every single public holiday, including Christmas and New Year's.", "logistics", 128),
    ("How many people are allowed on one boat?", "<p>Our fiberglass hulls are strictly certified by local authorities. Our smallest boats hold <strong>7 people</strong>, while our massive extended boats can safely accommodate up to <strong>12 to 14 passengers</strong>.</p>", "Our commercial fiberglass boats safely hold between 7 and 14 passengers depending on the vessel size.", "logistics", 129),
    ("Can we bring alcohol on the boat?", "<p>Yes! We highly encourage groups to bring their own coolers, beers, or champagne—especially for our famous <strong>Sunset Cruises</strong>. We just ask that you dispose of all cans/bottles safely onshore and never in the lake.</p>", "Yes! Bring your own coolers, beers, and champagne. Just do not litter in the lake.", "logistics", 130),
    ("What is the cancellation policy?", "<p>Rafiki operates with a highly flexible cancellation policy. If you cancel your boat ride <strong>24 hours prior</strong>, you receive massive refunds. If weather prevents the ride, we reschedule you for free.</p>", "Highly flexible. Fully refundable up to 24 hours prior. Weather cancellations are rescheduled for free.", "booking", 131),
    ("Do you rent out self-drive boats?", "<p><strong>No.</strong> Operating a boat on Lake Naivasha requires a massive amount of local geographic and hippo-behavioral knowledge. We strictly only offer captained rides to ensure absolute safety.</p>", "No. Operating a boat here requires extreme local knowledge of hippo behavior. We only offer captained rides.", "booking", 132),
    ("Can Rafiki organize accommodation for me?", "<p>We do not directly own a hotel, but we can recommend the absolute best lodges in Naivasha (like Sopa Resort, Enashipai, or Camp Carnelley's) depending entirely on your budget.</p>", "We do not own a hotel, but we happily provide free recommendations based on your budget.", "logistics", 133),
    ("Is it cheaper to book directly with Rafiki?", "<p><strong>Yes.</strong> Booking your boat ride directly through Rafiki via WhatsApp cuts out the massive commissions charged by third-party Nairobi tour operators or hotel booking desks.</p>", "Yes. Booking directly via our WhatsApp bypasses the massive commissions charged by hotels and tour agencies.", "pricing", 134),
    ("Can I change my booking time?", "<p>Yes. If you are delayed in Escarpment traffic, simply send a highly quick WhatsApp message to your Rafiki captain, and we will shift your time slot backward at absolutely zero cost.</p>", "Yes. Simply WhatsApp us if you are delayed in traffic and we will shift your slot for free.", "booking", 135),
    ("What are the peak hours for boat rides?", "<p>Peak traffic on the lake occurs between <strong>11:00 AM and 2:00 PM</strong>. To avoid the massive crowds and secure the best lighting, we constantly recommend 7:00 AM or 4:30 PM rides.</p>", "Peak hours are 11:00 AM to 2:00 PM. Book 7:00 AM or 4:30 PM to avoid the massive crowds.", "logistics", 136),
    ("Do you offer corporate team building packages?", "<p>Yes! Rafiki regularly handles massive corporate retreats. We can deploy a <strong>flotilla of 5 to 10 boats simultaneously</strong> and organize inter-boat races or photography challenges.</p>", "Yes! We handle massive corporate retreats and can deploy multi-boat flotillas simultaneously.", "booking", 137),
    ("Can we play music on the boat?", "<p>Yes, many of our boats come equipped with minor bluetooth speakers, and you are welcome to bring yours. However, we ask that you <strong>keep the volume low near the hippo pods and breeding bird zones</strong>.</p>", "Yes, but we require low volume when positioned near the massive hippo pods and bird breeding zones.", "logistics", 138),
    ("How long does it take to get to Crescent Island by boat?", "<p>A direct, high-speed transfer from the Karagita Public Beach to Crescent Island takes roughly <strong>15 to 20 minutes</strong> across the open lake water.</p>", "It takes roughly 15 to 20 minutes for a direct boat crossing from Karagita to Crescent Island.", "transport", 139),
    ("Do you charge per person or per boat?", "<p>We offer both options! Solo travelers and small groups can join a shared boat to pay <strong>per person</strong>. Alternatively, you can pay a flat rate <strong>per boat</strong> to secure an entirely private charter.</p>", "Both! You can pay per person on a shared ride, or a flat hourly rate for a fully private charter.", "pricing", 140),
    ("Can children go free on the boat?", "<p>Infants and highly young toddlers (Under 3 years old) generally ride for <strong>absolutely free</strong>. Older children (3-12) are typically charged at a discounted 'child rate'.</p>", "Infants under 3 ride essentially for free. Children aged 3-12 receive discounted child rates.", "pricing", 141),
    ("Is there phone network coverage on the lake?", "<p>Yes! Safaricom, Airtel, and Telkom all offer <strong>massive 4G coverage</strong> across almost 95% of the lake's surface, so you can live-stream your hippo safari directly to your followers.</p>", "Yes, massive 4G coverage is available across almost the entire lake surface from Safaricom and Airtel.", "logistics", 142),
    ("Where is the best place to eat near the Lake Naivasha boat launch?", "<p>Right at Karagita Public Beach! The shoreline is littered with massive, highly authentic fish shacks grilling fresh, whole <strong>Lake Naivasha Tilapia</strong> right out of the water.</p>", "Karagita Public Beach is famous for its authentic, lakeside shacks serving fresh, whole grilled Tilapia.", "logistics", 143),
    ("Can Rafiki organize a BBQ on the lake?", "<p>We do not cook on the fiberglass boats, but we can organize a massive <strong>shoreline BBQ drop-off at Sanctuary Farm or Crescent Island</strong> as part of a highly customized full-day package.</p>", "No cooking on boats, but we can arrange a massive shoreline BBQ drop-off at Sanctuary Farm.", "booking", 144),
    ("What happens if my boat runs out of fuel?", "<p>This is impossible with Rafiki. Our captains check fuel tanks daily, and we operate on a highly robust backup system. If a motor were to mechanically fail, a <strong>secondary rescue boat is deployed instantly</strong>.</p>", "Impossible. We check fuel daily, and if a motor mechanically fails, a rescue boat is deployed instantly.", "safety", 145),
    ("Do you cater to international filming crews?", "<p>Yes! Rafiki regularly partners with massive international documentary crews and influencers. We provide <strong>extended, deeply silent electric-motor tracking rides</strong> specifically for 4K wildlife videography.</p>", "Yes, we regularly partner with massive documentary crews to provide completely silent, extended tracking rides.", "booking", 146),
    ("Can I propose to my partner on the boat?", "<p><strong>Massively yes.</strong> Our 'Romantic Proposal Sunset Cruise' is our highest-rated premium package. We can slow the boat in front of Crescent Island right as the sun dips below the horizon.</p>", "Massively yes. Our 'Sunset Proposal Cruise' is highly rated and designed specifically for breathtaking moments.", "booking", 147),
    ("How do I identify my Rafiki boat at the beach?", "<p>Once you arrive at Karagita Public beach, simply <strong>call or WhatsApp your assigned captain</strong>. They will walk directly to your car and physically escort you to the Rafiki-branded fiberglass boats.</p>", "Call or WhatsApp your assigned Rafiki captain upon arrival. They will physically escort you to the boat.", "logistics", 148),
    ("Are your prices higher during the peak wildebeest migration season?", "<p><strong>Absolutely not.</strong> One of Rafiki's core values is transparency. Our boat ride pricing structure remains completely flat and fixed throughout the entire July-August high season.</p>", "Absolutely not. Our pricing is 100% fixed and transparent, even during the massive July-August migration season.", "pricing", 149),
    ("Do you offer multi-day passing?", "<p>Yes! If you are a photographer staying for a week, we offer massive <strong>multi-day boat charter discounts</strong> allowing you to spend hours on the water every morning capturing the exact perfect shot.</p>", "Yes, we offer massive multi-day charter discounts for wildlife photographers shooting extensively over several mornings.", "pricing", 150),
]

print("--- Starting Batch 1 FAQ Generation ---")
for q, a, plain, intent, order in faqs:
    F(q, a, plain, intent, order)
print("--- Batch 1 Complete (50 FAQs Injected) ---")
