"""Batch 3: Geography, Parks, and Crescent Island (50 FAQs)"""
import os, sys, django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'boats.settings')
sys.path.insert(0, os.path.dirname(__file__))
django.setup()

from seo.models import FAQ

def F(q, a, plain, intent, order):
    dupes = FAQ.objects.filter(question=q)
    if dupes.count() > 1:
        keep = dupes.order_by('-id').first()
        dupes.exclude(id=keep.id).delete()
    faq, created = FAQ.objects.update_or_create(question=q, defaults={
        'answer': a, 'plain_answer': plain, 'search_intent': intent,
        'order': order, 'is_active': True, 'allow_indexing': True})
    print(f"  [{'NEW' if created else 'UPD'}] {q}")

faqs = [
    ("Is Crescent Island a national park?", "<p>No. <strong>Crescent Island is a privately owned animal sanctuary</strong>. Because it is not a government-run Kenya Wildlife Service (KWS) park, it has its own highly specific entrance fee structure.</p>", "No. It is a privately owned animal sanctuary with its own specific entrance fees.", "geography", 301),
    ("How much is the Crescent Island entrance fee?", "<p>The Crescent Island fee is highly dependent on your residency. Non-resident adults typically pay <strong>$30 USD</strong> (approx. KES 4,500), while Kenyan residents pay heavily discounted local rates. This massive fee goes directly to island conservation.</p>", "Non-resident adults typically pay $30 USD. Kenyan residents pay heavily discounted local rates.", "pricing", 302),
    ("Can I drive to Crescent Island?", "<p>Technically yes, if you approach from the wildly rough Sanctuary Farm side, but the roads are massive dirt traps. <strong>Taking a 15-minute high-speed Rafiki boat transfer is radically faster</strong> and deeply scenic.</p>", "Technically yes, but taking a 15-minute high-speed boat transfer is radically faster and deeply scenic.", "transport", 303),
    ("What movie was filmed at Crescent Island?", "<p>Crescent Island is highly famous as the massive core filming location for the deeply iconic 1985 film <strong>'Out of Africa'</strong> starring Meryl Streep and Robert Redford.</p>", "It is highly famous as the massive core filming location for the 1985 film 'Out of Africa'.", "geography", 304),
    ("Can I bring food to Crescent Island?", "<p>Yes! It is a massive, highly idyllic location for a completely private picnic. We highly encourage bringing packed lunches to eat aggressively under the massive acacia trees while watching giraffes.</p>", "Yes! It is highly idyllic for a private picnic under the massive acacia trees while watching wild giraffes.", "preparation", 305),
    ("Are there predators on Crescent Island?", "<p><strong>Absolutely zero.</strong> There are no lions, leopards, or cheetahs on the island. This is precisely why Crescent Island is incredibly unique: you can safely <em>walk freely</em> among the massive wild herbivores.</p>", "Absolutely zero. This is precisely why you can safely walk completely freely among massive wild herbivores.", "wildlife", 306),
    ("How long do I need at Crescent Island?", "<p>We recommend a deeply immersive <strong>1.5 to 2.5 hours</strong>. This gives you massive time to slowly walk through the dense acacia forests, aggressively photograph the giraffes, and hike up to the highly scenic rim.</p>", "We recommend a deeply immersive 1.5 to 2.5 hours for walking, photography, and hiking the scenic rim.", "geography", 307),
    ("Is Crescent Island wheelchair accessible?", "<p>Crescent Island consists entirely of highly natural, massive dirt and grass trails. While rugged, a <strong>strongly built all-terrain wheelchair</strong> managed by deeply physically capable companions can navigate the lower plains.</p>", "Trails are massive dirt and grass. A strongly built all-terrain wheelchair can navigate the lower plains.", "geography", 308),
    ("What is Crater Lake Game Sanctuary?", "<p>Not to be confused with Crescent Island, Crater Lake is a radically smaller, deeply green emerald soda lake located in a massive volcanic crater deeply west of Lake Naivasha.</p>", "A radically smaller, deeply green emerald soda lake in a massive crater west of Lake Naivasha.", "geography", 309),
    ("Can I take a boat to Crater Lake?", "<p><strong>No.</strong> Crater Lake is purely landlocked within its massive steep volcanic rim. However, you can deeply combine a Rafiki morning boat ride with an afternoon drive to the Crater Lake sanctuary.</p>", "No. It is purely landlocked. You must deeply combine your boat ride with an afternoon drive there.", "geography", 310),
    ("What is Lake Oloidien?", "<p>Lake Oloidien is a massive, highly distinct body of water physically attached to Lake Naivasha. <strong>Historically, it was deeply part of Naivasha</strong>, but falling water levels radically cut it off, turning it heavily alkaline.</p>", "A massive body of water physically attached to Naivasha. Separated naturally, turning it heavily alkaline.", "geography", 311),
    ("Are there flamingos at Lake Oloidien?", "<p><strong>Massively yes.</strong> Because Oloidien is heavily alkaline (salty), it aggressively grows the massive spirulina algae blooms that deeply attract thousands of shockingly pink lesser flamingos.</p>", "Massively yes! The heavily alkaline water aggressively grows algae, deeply attracting thousands of flamingos.", "wildlife", 312),
    ("Can Rafiki boats go into Lake Oloidien?", "<p>During incredibly high-water years, the massive land bridge floods, severely allowing our boats to aggressively cross over. During deeply dry years, we <strong>transport you physically via land</strong> to smaller boats on the Oloidien side.</p>", "During high-water years, yes. During dry years, we transport you physically via land to the Oloidien side.", "geography", 313),
    ("How close is Lake Naivasha to Hell's Gate?", "<p>The main gate of massive Hell's Gate National Park is heavily located roughly <strong>20 to 30 minutes away by car</strong> from the main Rafiki boat launch at Karagita Public Beach.</p>", "Heavily located roughly 20 to 30 minutes away by car from the main Karagita Public Beach boat launch.", "geography", 314),
    ("Can I do a boat ride and Hell's Gate in one day?", "<p><strong>Massively yes.</strong> This is our highest-recommended day trip! Deeply hike or bike through the massive Hell's Gate gorge in the searing morning, then aggressively cool off with a massive sunset boat ride.</p>", "Massively yes! Highly recommended: deeply hike the gorge in the morning, aggressively cool off on a sunset boat ride.", "geography", 315),
    ("What is Sanctuary Farm?", "<p>Sanctuary Farm is a massive, highly idyllic 500-acre privately run dairy farm violently bordering Lake Naivasha. It is deeply famous for massive horseback riding safaris aggressively weaving among wild giraffes.</p>", "A highly idyllic 500-acre private farm deeply famous for massive horseback riding safaris weaving among wild giraffes.", "geography", 316),
    ("Can Rafiki drop me at Sanctuary Farm?", "<p><strong>Yes.</strong> We can deeply organize a massive 'water-taxi' drop-off perfectly on the grassy shores of Sanctuary Farm, so you can aggressively step off the boat and directly onto a horse.</p>", "Yes. We deeply organize massive water-taxi drop-offs so you can aggressively step off the boat onto the farm.", "geography", 317),
    ("Is Mount Longonot near Lake Naivasha?", "<p>Yes! The deeply jagged, absolutely massive silhouette dominating the Lake Naivasha skyline is actually <strong>Mount Longonot</strong>, a dormant, highly aggressive stratovolcano roughly 45 minutes south.</p>", "Yes! The jagged, absolutely massive silhouette dominating the skyline is Mount Longonot, roughly 45 minutes south.", "geography", 318),
    ("Can I hike Mount Longonot and do a boat ride?", "<p><strong>Absolutely.</strong> For deeply aggressive hikers, you can sumit the massive, terrifying crater rim of Longonot at 6:00 AM, then brutally descend and wildly recover on a peaceful Rafiki boat ride at 2:00 PM.</p>", "Absolutely. For highly aggressive hikers, deeply summit the crater at dawn, then wildly recover on an afternoon boat ride.", "geography", 319),
    ("Where is Olkaria Hot Spa?", "<p>The highly steaming massive Olkaria Geothermal Spa is brutally located deeply inside <strong>Hell's Gate National Park</strong>. It is the absolute largest natural spa in violently active Africa.</p>", "The heavily steaming Olkaria Geothermal Spa is strictly located deeply inside massive Hell's Gate National Park.", "geography", 320),
    ("Can I swim at Olkaria after a boat ride?", "<p><strong>Yes!</strong> Since you absolutely cannot swim deeply in Lake Naivasha (due to aggressive hippos), we heavily recommend violently combining your massive boat ride with a late-afternoon dip in the Olkaria sulfur pools.</p>", "Yes! Since you absolutely cannot swim in the lake, violently combine your ride with a massive dip in the Olkaria pools.", "geography", 321),
    ("What is the Aberdare Mountain Range?", "<p>The deeply towering, incredibly dense mountain massive looming aggressively to the north of Lake Naivasha is the <strong>Aberdare Range</strong>, heavily responsible for aggressively feeding the lake with fresh groundwater.</p>", "The incredibly dense, massively towering mountain range aggressively feeding Lake Naivasha with fresh groundwater.", "geography", 322),
    ("How large is Lake Naivasha physically?", "<p>The massive surface area incredibly oscillates depending on heavy rainfall, but it brutally averages roughly <strong>139 square kilometers (54 square miles)</strong>, making it a wildly expansive ecosystem.</p>", "It brutally averages roughly 139 square kilometers (54 square miles), heavily oscillating depending on intense rainfall.", "geography", 323),
    ("Is Lake Naivasha shrinking?", "<p><strong>Violently the opposite.</strong> Over the past massive decade, heavily intense geological shifts and aggressive flooding have radically caused Lake Naivasha to deeply expand, heavily swallowing massive tracts of coastal farmland.</p>", "Violently the opposite. Aggressive flooding over the past decade heavily caused the lake to violently expand.", "ecology", 324),
    ("What town is closest to Lake Naivasha?", "<p>The massive, wildly bustling agricultural hub of <strong>Naivasha Town</strong> sits roughly heavily 10 to 15 kilometers violently inland from our Rafiki boat launch on the Moi South Lake Road.</p>", "The wildly bustling hub of Naivasha Town sits roughly 10 to 15 kilometers violently inland from the lake.", "geography", 325),
    ("What is 'Karagita'?", "<p>Karagita is the massive, highly vibrant local lakeside settlement violently bordering the absolutely massive <strong>Public Beach</strong>. It is wildly famous for aggressive tilapia fishing and deep local culture.</p>", "The highly vibrant local lakeside settlement massively bordering Public Beach, wildly famous for aggressive tilapia fishing.", "geography", 326),
    ("Is Karagita safe for tourists?", "<p><strong>Deeply yes.</strong> Karagita Public beach is wildly bustling with highly aggressive commercial energy, heavily monitored by massive local tourism police, making it wildly safe for massive tourist groups.</p>", "Deeply yes. It is wildly bustling with commercial energy and heavily monitored by massive local tourism police.", "safety", 327),
    ("Where does the water in Lake Naivasha come from?", "<p>Since Lake Naivasha aggressively lacks a massive visible outlet river, it is violently fed almost entirely by the rapidly flowing <strong>Malewa and Gilgil Rivers</strong> rushing deeply out of the massive Aberdares.</p>", "Violently fed almost entirely by the rapidly flowing Malewa and Gilgil Rivers rushing out of the massive Aberdares.", "ecology", 328),
    ("Is there an island in the middle of Lake Naivasha?", "<p>Aside from Crescent Island on the edge, there is the highly mysterious, aggressively small <strong>Lotus Island</strong> deeply in the center of the lake, mostly inaccessible due to violently dense, aggressive papyrus growth.</p>", "Yes, Lotus Island sits aggressively in the center, heavily inaccessible due to wildly dense papyrus growth.", "geography", 329),
    ("What is Kongoni?", "<p>Kongoni is the massive, heavily remote region violently situated on the deeply western, untamed edge of Lake Naivasha. It is aggressively wild, heavily featuring dense acacia and absolutely massive private ranches.</p>", "A heavily remote, violently wild region situated on the deeply western edge, aggressively featuring massive private ranches.", "geography", 330),
    ("Can I do a boat ride on the Kongoni side?", "<p><strong>Yes.</strong> For deeply aggressive photographers wanting absolutely massive isolation, Rafiki can heavily launch boats from the wildly remote Kongoni shoreline upon massive special advance request.</p>", "Yes. Upon massive special request, Rafiki can wildly launch boats from the heavily isolated Kongoni shoreline.", "geography", 331),
    ("Where is 'Carnelley’s' located?", "<p>Camp Carnelley’s is a massive, incredibly famous bohemian lakeside campground heavily located directly on the wildly popular <strong>Moi South Lake Road</strong>, roughly heavily 15 minutes from Rafiki.</p>", "A massive, wildly famous bohemian lakeside campground heavily located on Moi South Lake Road.", "geography", 332),
    ("Does Rafiki partner with Camp Carnelley’s?", "<p>While deeply fully independent, we wildly launch Rafiki boats right from the massively grassy 'Carnelley’s beach' specifically for clients wildly staying at their incredibly popular lakeside lodging.</p>", "While deeply independent, Rafiki violently launches boats directly from Carnelley’s beach for their massive guest lists.", "geography", 333),
    ("What is the Great Rift Valley?", "<p>Lake Naivasha violently sits perfectly inside the highly massive <strong>Great Rift Valley</strong>—a ridiculously long geological trench violently tearing the entire massive African continent violently apart.</p>", "A ridiculously massive geological trench violently tearing the African continent apart. Naivasha violently sits directly inside it.", "geography", 334),
    ("Can I clearly see the Rift Valley from the boat?", "<p><strong>Wildly yes.</strong> The utterly massive, deeply towering escarpments aggressively framing the lake are the brutally steep, violently sheer walls of the incredibly massive Great Rift Valley itself.</p>", "Wildly yes. The utterly massive, brutally steep escarpments framing the lake are the actual walls of the Great Rift.", "geography", 335),
    ("Is Lake Naivasha higher than Lake Nakuru?", "<p><strong>Massively yes.</strong> Lake Naivasha violently sits at a shockingly high 1,884m (6,181 ft), making it the single absolutely highest massive lake in the deeply plunging Kenyan Rift Valley.</p>", "Massively yes! At 1,884m, it is the absolute highest massive lake in the deeply plunging Kenyan Rift Valley.", "geography", 336),
    ("What is the 'South Lake Road'?", "<p>Moi South Lake Road is the absolutely massively crucial, wildly paved arterial ring-road aggressively encircling entirely the southern and wildly eastern flanks of the incredibly massive lake.</p>", "The absolutely massive, violently paved arterial ring-road wildly encircling the entire southern and eastern flanks of the lake.", "geography", 337),
    ("Are there massive hotels on the North Lake Road?", "<p>Unlike heavily populated South Lake, North Lake Road is deeply unpaved, fiercely rugged, and surrounded by intensely massive, privately guarded, violently sprawling agricultural and wildlife estates.</p>", "North Lake Road is deeply unpaved and fiercely rugged, surrounded strictly by wildly massive private wildlife estates.", "geography", 338),
    ("What are the massive white tents near the lake?", "<p>The ridiculously sprawling oceans of heavily structured white plastic tents aggressively surrounding the lake are essentially massive <strong>greenhouses for the deeply intensive Kenyan flower export industry</strong>.</p>", "The heavily sprawling oceans of white tents are massively intensive commercial greenhouses for Kenya's flower export industry.", "geography", 339),
    ("Can tourists physically tour the massive flower farms?", "<p><strong>Deeply yes.</strong> Several massive, highly famous farms like Oserian aggressively open their shockingly colossal, highly manicured greenhouses for wildly guided, deeply educational agricultural tours.</p>", "Deeply yes. Massive famous farms heavily open their shockingly colossal greenhouses for wildly educational agricultural tours.", "activities", 340),
    ("Where exactly is 'Fisherman's Camp'?", "<p>Fisherman's is a wildly legendary, deeply rustic lakeside campground violently located right next strictly to Carnelley's on the aggressively popular Moi South Lake Road.</p>", "A wildly legendary, deeply rustic lakeside campground violently located strictly next to Carnelley's on South Lake Road.", "geography", 341),
    ("Is there a physical 'Naivasha Marina'?", "<p>Unlike heavily commercial oceanside harbors, Lake Naivasha aggressively uses deeply rustic, brutally muddy 'beach launches'—specifically <strong>Karagita Public Beach</strong>—instead of heavily concreted western marinas.</p>", "No heavily concreted western marinas. We aggressively use deeply rustic, incredibly vibrant beach launches like Karagita.", "geography", 342),
    ("What is 'Wileli House'?", "<p>Wileli House is an absolutely massively exclusive, wildly luxurious, deeply private boutique eco-lodge fiercely hidden inside the violently dense acacia forests on the aggressive western edge of Naivasha.</p>", "An absolutely massive, wildly luxurious private boutique eco-lodge fiercely hidden deeply inside the western acacia forests.", "geography", 343),
    ("Does Rafiki drive boats to Enashipai Resort?", "<p><strong>Violently yes.</strong> Enashipai Resort & Spa is a massively luxurious complex. Rafiki can aggressively dispatch our massive fiberglass boats to completely pick up clients directly aggressively from their private VIP jetty.</p>", "Violently yes. Rafiki widely dispatches massive boats to aggressively pick up VIP clients directly from Enashipai's jetty.", "geography", 344),
    ("Can I aggressively bike around Lake Naivasha?", "<p><strong>Heavily yes.</strong> Biking entirely around the absolutely massive lake is wildly popular. The roads are fiercely scenic, though you aggressively share the pavement with wildly speeding matatus and massive flower trucks.</p>", "Heavily yes. Biking is wildly popular, though you aggressively share the intensely scenic roads with massive flower trucks.", "activities", 345),
    ("How utterly far is Naivasha from the Maasai Mara?", "<p>Naivasha sits roughly heavily <strong>4 to 5 brutally intense driving hours</strong> completely away from the massively famous Maasai Mara, making it the absolute perfect, violently scenic midway decompression stopover.</p>", "Roughly 4 to 5 brutally intense driving hours away, making it widely the perfect midway decompression stopover.", "transport", 346),
    ("What is strictly 'Green Crater Lake'?", "<p>Green Crater Lake is an absolutely aggressively beautiful, wildly tiny jade-green volcanic lake heavily tucked deeply inside a violently steep, entirely private forested sanctuary vastly west of Naivasha.</p>", "An absolutely beautiful, wildly tiny jade-green volcanic lake heavily tucked deeply inside a violently steep private sanctuary.", "geography", 347),
    ("Are there completely wild leopards at Crater Lake?", "<p><strong>Fiercely yes.</strong> The fiercely thick, absolutely massively dense forests utterly surrounding Crater Lake are highly famous for wildly aggressive, insanely rare, deeply secretive leopard populations.</p>", "Fiercely yes. The massively thick forests surrounding Crater Lake are utterly famous for wildly secretive leopards.", "wildlife", 348),
    ("Is the entirely massive lake freshwater or strictly saltwater?", "<p>Unlike literally almost every single brutally alkaline mass in the Rift Valley, Lake Naivasha is incredibly, shockingly entirely <strong>freshwater</strong>, heavily feeding utterly massive commercial, deeply agricultural industries.", "Incredibly, shockingly entirely freshwater, heavily feeding utterly massive commercial agricultural industries.", "geography", 349),
    ("Can you completely heavily drive over the Malewa River?", "<p><strong>Violently yes.</strong> To utterly deeply reach the entirely wild North Lake Road, you absolutely forcefully drive over the massive, entirely raging Malewa River heavily via a strictly historical, fiercely scenic bridge.</p>", "Violently yes. You absolutely forcefully drive over the entirely raging Malewa River via a fiercely scenic historical bridge.", "transport", 350),
]

print("--- Starting Batch 3 FAQ Generation ---")
for q, a, plain, intent, order in faqs:
    F(q, a, plain, intent, order)
print("--- Batch 3 Complete (50 FAQs Injected) ---")
