# Generated by Django 6.0.1 on 2026-09-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Nova Boat Rides Naivasha', max_length=150)),
                ('legal_name', models.CharField(default='Nova Boat Rides Naivasha Ltd', max_length=150)),
                ('tagline', models.CharField(default='Naivasha starts here.', max_length=200)),
                ('supporting_proposition', models.CharField(default='Boat rides, hotel departures and curated stays around Lake Naivasha — planned through one local team.', max_length=300)),
                ('phone_display', models.CharField(default='+254 700 000 000', max_length=50)),
                ('phone_e164', models.CharField(default='+254700000000', max_length=30)),
                ('whatsapp_number', models.CharField(default='254700000000', max_length=30)),
                ('email', models.EmailField(default='hello@novaboatrider.com', max_length=254)),
                ('standard_launch_name', models.CharField(default='Nova Lake Base, South Lake Road, Naivasha', max_length=150)),
                ('standard_launch_lat', models.DecimalField(decimal_places=6, default=-0.7572, max_digits=9)),
                ('standard_launch_lng', models.DecimalField(decimal_places=6, default=36.3542, max_digits=9)),
                ('operating_hours', models.CharField(default='Daily 6:30 AM – 6:30 PM', max_length=100)),
                ('default_currency', models.CharField(default='KES', max_length=5)),
                ('gbp_url', models.URLField(blank=True, default='')),
                ('directions_summary', models.TextField(blank=True, default='Accessible via South Lake Road, Naivasha. Private parking, secure boarding jetty, and guest lounge on site.')),
                ('booking_notice', models.CharField(default='Advance notice recommended for hotel pickups, Crescent Island walks, and sunset charters.', max_length=255)),
                ('last_verified_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
