# Generated by Django 6.0.1 on 2026-09-27 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='e.g. Crescent Island Game Sanctuary, Kenya Wildlife Service', max_length=150)),
                ('service_name', models.CharField(help_text='e.g. Sanctuary Entry, Park Entry', max_length=150)),
                ('visitor_type', models.CharField(choices=[('CITIZEN', 'Kenyan Citizen'), ('RESIDENT', 'East African Resident'), ('NON_RESIDENT', 'Non-Resident (International)'), ('STUDENT', 'Student'), ('ALL', 'All Visitors')], default='ALL', max_length=30)),
                ('adult_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('student_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, default='https://www.crescentisland.co/')),
                ('source_name', models.CharField(blank=True, default='Official Conservation Schedule', max_length=150)),
                ('last_verified_at', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'External Fee',
                'verbose_name_plural': 'External Fees',
                'ordering': ['provider_name', 'visitor_type'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='closing_time',
            field=models.CharField(default='18:30', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='county',
            field=models.CharField(default='Nakuru County', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='meta/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_business_profile_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, default='https://maps.google.com/?q=-0.762030,36.425790'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='locality',
            field=models.CharField(default='Karagita, Naivasha', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_time',
            field=models.CharField(default='06:30', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='street_address',
            field=models.CharField(default='Karagita Beach, Moi South Lake Road', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tripadvisor_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='directions_summary',
            field=models.TextField(blank=True, default='Located at Karagita Beach off Moi South Lake Road, Naivasha (8 km from Naivasha Town). Dedicated briefing pavilion, secure perimeter parking, life jacket fitting station, and direct boat jetty access.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='hello@novaboatridesnaivasha.co.ke', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='standard_launch_lat',
            field=models.DecimalField(decimal_places=6, default=-0.76203, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='standard_launch_lng',
            field=models.DecimalField(decimal_places=6, default=36.42579, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='standard_launch_name',
            field=models.CharField(default='Nova Karagita Base, Lake Naivasha', max_length=150),
        ),
    ]
