# Generated by Django 6.0.1 on 2026-09-08 09:29

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('property_type', models.CharField(choices=[('RESORT', 'Lakeside Resort'), ('LODGE', 'Safari Lodge'), ('CAMP', 'Tented Camp'), ('BOUTIQUE', 'Boutique Hotel / Villa'), ('OTHER', 'Other Lakeside Property')], default='RESORT', max_length=20)),
                ('public_summary', models.TextField(help_text='Public-approved location context and lake proximity')),
                ('website_url', models.URLField(blank=True, help_text='Official hotel website')),
                ('contact_name_private', models.CharField(blank=True, help_text='PRIVATE ops contact name', max_length=150)),
                ('contact_phone_private', models.CharField(blank=True, help_text='PRIVATE ops phone number', max_length=50)),
                ('contact_email_private', models.EmailField(blank=True, help_text='PRIVATE ops email', max_length=254)),
                ('partnership_status', models.CharField(choices=[('PROSPECT', 'Prospect / Unverified'), ('VERIFIED', 'Verified Lake Access / Operational'), ('INACTIVE', 'Inactive')], default='PROSPECT', max_length=20)),
                ('marketing_permission', models.BooleanField(default=False, help_text='Locked rule: Must be True before any co-branding or public partnership claims')),
                ('public_page_enabled', models.BooleanField(default=False, help_text='Locked rule: Public page is disabled by default. Enabled only with permission and verified service details')),
                ('referral_code', models.CharField(blank=True, max_length=30)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate %', max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='partners/webp/')),
                ('webp_mobile', models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='partners/webp/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Partner',
                'verbose_name_plural': 'Hotel Partners',
                'ordering': ['order', 'name'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HotelServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sopa Main Jetty, North Lake Access Point', max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_mode', models.CharField(choices=[('PARTNER_JETTY', 'Direct Hotel Jetty Boarding'), ('PARTNER_TRANSFER', 'Road Vehicle Transfer to Nova Base'), ('BOAT_POSITIONING', 'Boat Positioned to Approved Access Point'), ('REFERRAL_ONLY', 'Standard Launch Departure')], default='PARTNER_TRANSFER', max_length=30)),
                ('public_instructions', models.TextField(help_text='Guest-facing meeting instructions, security gate guidance, and boarding details')),
                ('private_ops_notes', models.TextField(blank=True, help_text='PRIVATE captain/ops notes: water depth, mud risks, gate contact, positioning time')),
                ('operating_window', models.CharField(default='07:00 – 17:30', max_length=100)),
                ('notice_hours', models.PositiveIntegerField(default=24, help_text='Required advance notice in hours for boat positioning or gate clearance')),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_points', to='partners.hotelpartner')),
            ],
            options={
                'verbose_name': 'Hotel Service Point',
                'verbose_name_plural': 'Hotel Service Points',
                'ordering': ['hotel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelTourService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_mode', models.CharField(choices=[('PARTNER_JETTY', 'Direct Hotel Jetty Boarding'), ('PARTNER_TRANSFER', 'Road Vehicle Transfer to Nova Base'), ('BOAT_POSITIONING', 'Boat Positioned to Approved Access Point'), ('REFERRAL_ONLY', 'Standard Launch Departure')], default='PARTNER_JETTY', max_length=30)),
                ('positioning_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Logistics or positioning fee in KES (0 if complimentary or included in tier)', max_digits=10)),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_times', models.CharField(default='Morning, Afternoon', max_length=100)),
                ('notice_hours_override', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_manual_confirmation', models.BooleanField(default=True, help_text='If True, quote flags that boat positioning requires operations sign-off')),
                ('is_active', models.BooleanField(default=True)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_services', to='partners.hotelservicepoint')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Hotel Tour Service Matrix',
                'verbose_name_plural': 'Hotel Tour Service Matrix',
                'ordering': ['service_point', 'tour'],
                'unique_together': {('service_point', 'tour')},
            },
        ),
    ]
