# Generated by Django 6.0.1 on 2026-09-27 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('NO_FORMAL_PARTNERSHIP', 'No Formal Partnership'), ('REFERRAL', 'Referral / Information Only'), ('OPERATIONAL', 'Operational Coordination'), ('CONTRACTED', 'Formally Contracted Partner'), ('DIRECTLY_MANAGED', 'Directly Managed Facility')], default='OPERATIONAL', max_length=30)),
                ('access_mode', models.CharField(choices=[('DIRECT_JETTY', 'Direct Hotel Jetty Mooring'), ('ROAD_TRANSFER', 'Road Transfer to Nova Karagita Base'), ('NEARBY_JETTY', 'Boarding via Adjacent/Nearby Jetty'), ('BOAT_POSITIONING', 'Boat Positioning to Approved Shoreline'), ('SUBJECT_TO_CONFIRMATION', 'Subject to Operations Confirmation'), ('UNAVAILABLE', 'Water Access Currently Unavailable')], default='DIRECT_JETTY', max_length=30)),
                ('access_status', models.CharField(choices=[('VERIFIED_ACTIVE', 'Verified Active'), ('VERIFIED_ON_REQUEST', 'Verified on Prior Request'), ('TEMPORARILY_UNAVAILABLE', 'Temporarily Unavailable'), ('UNVERIFIED', 'Unverified / Pending Audit')], default='VERIFIED_ACTIVE', max_length=30)),
                ('positioning_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('advance_notice_hours', models.PositiveIntegerField(default=2)),
                ('water_level_dependent', models.BooleanField(default=False)),
                ('property_approval_required', models.BooleanField(default=False)),
                ('last_verified_at', models.DateField(auto_now=True)),
                ('verified_by', models.CharField(default='Nova Operations Team', max_length=100)),
                ('public_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_info', to='partners.hotelpartner')),
            ],
            options={
                'verbose_name': 'Hotel Access Specification',
                'verbose_name_plural': 'Hotel Access Specifications',
            },
        ),
    ]
