# Generated by Django 6.0.1 on 2026-09-08 09:29

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stays', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tagline', models.CharField(default='Stay + Ride + Explore', max_length=200)),
                ('summary', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='packages/webp/')),
                ('webp_mobile', models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='packages/webp/')),
                ('duration_days', models.PositiveIntegerField(default=2)),
                ('duration_nights', models.PositiveIntegerField(default=1)),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('price_basis', models.CharField(default='per couple / 1 night + boat ride', max_length=100)),
                ('includes_hotel_origin_pickup', models.BooleanField(default=True)),
                ('includes_crescent_island', models.BooleanField(default=False)),
                ('includes_transfers', models.BooleanField(default=False)),
                ('itinerary_summary', models.TextField(blank=True, help_text='Chronological itinerary narrative')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('verified_at', models.DateField(auto_now=True)),
                ('accommodation_properties', models.ManyToManyField(blank=True, related_name='packages', to='stays.accommodationproperty')),
                ('eligible_tours', models.ManyToManyField(blank=True, related_name='packages', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['order', 'name'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PackageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('component_type', models.CharField(choices=[('BOAT', 'Lake Boat Safari'), ('HOTEL', 'Lakeside Accommodation'), ('TRANSFER', 'Private Road Transfer'), ('ACTIVITY', "Crescent Island / Hell's Gate Adventure"), ('MEAL', 'Lakeside Dining / Picnic')], default='BOAT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Component',
                'verbose_name_plural': 'Package Components',
                'ordering': ['package', 'order'],
            },
        ),
    ]
