# Generated by Django 6.0.1 on 2026-09-08 09:29

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(max_length=350)),
                ('body', models.TextField(help_text='Detailed tour description')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('capacity', models.PositiveIntegerField(default=8)),
                ('is_private', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=True)),
                ('hotel_pickup_available', models.BooleanField(default=True)),
                ('standard_departure', models.CharField(default='Nova Lake Base or Approved Partner Jetty', max_length=200)),
                ('best_for', models.CharField(default='Couples, Families, First-time visitors', max_length=200)),
                ('route_narrative', models.TextField(blank=True, help_text='Detailed route and scenic narrative')),
                ('what_guests_may_see', models.TextField(blank=True, help_text='Factual wildlife and scenery expectations without guaranteed sightings')),
                ('inclusions', models.TextField(blank=True, default='Certified captain guide\nLife jackets (adult & child sizes)\nBoat and fuel\nMineral water')),
                ('exclusions', models.TextField(blank=True, default='Crescent Island sanctuary entry fee (payable direct)\nGratuities / tips\nPersonal travel insurance')),
                ('safety_briefing', models.TextField(blank=True, default='All rides are skippered by licensed local captains. Life jackets are mandatory while on open water. Safe distance is maintained from all wildlife.')),
                ('child_policy', models.TextField(blank=True, default='Children of all ages are welcome with parental supervision. Specialized child-size life jackets are fitted before departure.')),
                ('weather_policy', models.TextField(blank=True, default='Lake Naivasha weather can shift quickly in the late afternoon. If wind or water conditions exceed safety thresholds, departure may be rescheduled or rerouted.')),
                ('cancellation_policy', models.TextField(blank=True, default='Full refund or complimentary reschedule if cancelled due to adverse lake weather conditions.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='tours/webp/')),
                ('webp_mobile', models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='tours/webp/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('verified_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['order', 'name'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price_mode', models.CharField(choices=[('FLAT', 'Flat Fee'), ('PER_PERSON', 'Per Person')], default='FLAT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('description', models.TextField(blank=True)),
                ('operational_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('eligible_tours', models.ManyToManyField(blank=True, related_name='eligible_addons', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Add-On',
                'verbose_name_plural': 'Add-Ons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 1–4 Guests, 5–8 Guests, Full Boat', max_length=100)),
                ('min_guests', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=8)),
                ('mode', models.CharField(choices=[('SHARED', 'Shared Boat'), ('PRIVATE', 'Private Charter')], default='SHARED', max_length=20)),
                ('resident_type', models.CharField(choices=[('RESIDENT', 'Kenyan Resident'), ('NON_RESIDENT', 'Non-Resident / International')], default='RESIDENT', max_length=20)),
                ('pricing_unit', models.CharField(choices=[('PER_PERSON', 'Per Person'), ('PER_BOAT', 'Per Boat / Charter')], default='PER_PERSON', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Price Tier',
                'verbose_name_plural': 'Tour Price Tiers',
                'ordering': ['tour', 'resident_type', 'amount'],
            },
        ),
    ]
