# Generated by Django 6.0.1 on 2026-09-27 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='standard_departure',
            field=models.CharField(default='Nova Karagita Base or Approved Partner Jetty', max_length=200),
        ),
        migrations.CreateModel(
            name='ExperienceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 1-Hour Private Charter, Shared Seat', max_length=150)),
                ('pricing_model', models.CharField(choices=[('PER_PERSON', 'Per Person'), ('PER_BOAT', 'Per Boat'), ('PER_GROUP', 'Per Group'), ('FROM_PRICE', 'From Price'), ('CUSTOM_QUOTE', 'Custom Quote')], default='PER_BOAT', max_length=30)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('audience_type', models.CharField(choices=[('ALL', 'All Visitors'), ('KENYAN_CITIZEN', 'Kenyan Citizen'), ('KENYA_RESIDENT', 'Kenya Resident'), ('NON_RESIDENT', 'Non-Resident / International'), ('CHILD', 'Child'), ('GROUP', 'Corporate / Group')], default='ALL', max_length=30)),
                ('min_guests', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=7)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Experience Rate',
                'verbose_name_plural': 'Experience Rates',
                'ordering': ['experience', 'amount'],
            },
        ),
    ]
