# Generated by Django 6.0.1 on 2026-09-08 09:29

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('inventory_mode', models.CharField(choices=[('ENQUIRY', 'Enquiry / Request Availability'), ('ALLOTMENT', 'Provisional Allocation (Staff Confirmation)'), ('MANAGED', 'Managed Inventory (Confirmed by Nova)'), ('EXTERNAL_BOOK', 'External Booking / Referral')], default='ENQUIRY', help_text='Locked rule: Must accurately declare whether availability is live, provisional, or enquiry-only', max_length=20)),
                ('property_type', models.CharField(choices=[('RESORT', 'Lakeside Resort'), ('LODGE', 'Safari Lodge'), ('CAMP', 'Tented Camp'), ('BOUTIQUE', 'Boutique Hotel / Villa'), ('COTTAGES', 'Lakeside Cottages')], default='RESORT', max_length=20)),
                ('address', models.CharField(default='Lake Naivasha, Kenya', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('summary', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('why_nova_recommends', models.TextField(help_text='Why this property works with a Nova lake day: water access, jetty proximity, family suitability')),
                ('amenities', models.TextField(default='Lakefront Gardens, Swimming Pool, Restaurant & Bar, Wi-Fi, Secure Parking', help_text='Comma-separated or bullet list of verified property amenities')),
                ('check_in_time', models.CharField(default='14:00', max_length=50)),
                ('check_out_time', models.CharField(default='10:00', max_length=50)),
                ('child_policy', models.TextField(blank=True, default='Children welcome. Extra beds and family rooms available upon request.')),
                ('cancellation_policy', models.TextField(blank=True, default='Cancellation policies depend on property terms and season.')),
                ('official_url', models.URLField(blank=True, help_text='Official website of the property')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stays/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='stays/webp/')),
                ('webp_mobile', models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='stays/webp/')),
                ('starting_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('price_basis', models.CharField(default='per room / night (BB)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('verified_at', models.DateField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('partner', models.ForeignKey(blank=True, help_text='Link to partner record if hotel-origin boat departures are supported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations', to='partners.hotelpartner')),
            ],
            options={
                'verbose_name': 'Accommodation Property',
                'verbose_name_plural': 'Accommodation Properties',
                'ordering': ['order', 'name'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard Lakeview Room, Cottage, Deluxe Suite', max_length=150)),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=1)),
                ('bed_configuration', models.CharField(default='1 King Bed or 2 Twin Beds', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stays/rooms/')),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='stays.accommodationproperty')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['property', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan', models.CharField(choices=[('RO', 'Room Only'), ('BB', 'Bed & Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Inclusive')], default='BB', max_length=10)),
                ('pricing_mode', models.CharField(choices=[('PER_ROOM', 'Per Room / Night'), ('PER_PERSON', 'Per Person / Night')], default='PER_ROOM', max_length=20)),
                ('resident_type', models.CharField(choices=[('RESIDENT', 'Kenyan Resident'), ('NON_RESIDENT', 'Non-Resident / International')], default='RESIDENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('inventory_quantity', models.PositiveIntegerField(default=5)),
                ('is_available', models.BooleanField(default=True)),
                ('verified_at', models.DateField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='stays.roomtype')),
            ],
            options={
                'verbose_name': 'Accommodation Rate',
                'verbose_name_plural': 'Accommodation Rates',
                'ordering': ['room_type', 'meal_plan', 'amount'],
            },
        ),
    ]
