# Generated by Django 6.0.1 on 2026-09-08 09:29

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('role_title', models.CharField(default='Senior Lake Captain', max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='crew/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='crew/webp/')),
                ('webp_mobile', models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='crew/webp/')),
                ('bio', models.TextField()),
                ('years_on_lake', models.PositiveIntegerField(default=10)),
                ('route_specialties', models.CharField(default='Hippo family territories, fish eagle calling, Crescent Island western approach', max_length=255)),
                ('languages', models.CharField(default='English, Swahili', max_length=120)),
                ('quote', models.CharField(default='The lake has its own rhythm. When you start early and respect the wind, every ride is smooth.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Captain',
                'verbose_name_plural': 'Captains',
                'ordering': ['order', 'name'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('author', models.CharField(default='Nova Lake Operations', max_length=100)),
                ('reviewer', models.CharField(default='Senior Captain Team', max_length=100)),
                ('category', models.CharField(choices=[('PLANNING', 'Trip Planning'), ('WILDLIFE', 'Wildlife & Birds'), ('HOTEL_LOGISTICS', 'Hotel & Jetty Logistics'), ('SAFETY', 'Water Safety & Weather'), ('CAPTAIN_LOG', "Captain's Field Log")], default='PLANNING', max_length=30)),
                ('direct_quick_answer', models.TextField(blank=True, help_text='AEO concise direct answer block for AI search extraction')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('webp_image', models.ImageField(blank=True, null=True, upload_to='journal/webp/')),
                ('webp_mobile', models.ImageField(blank=True, null=True, upload_to='journal/webp/')),
                ('published_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('verified_at', models.DateField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Guide Article',
                'verbose_name_plural': 'Guide Articles',
                'ordering': ['-is_featured', '-published_at'],
            },
            bases=(utils.OptimizedImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('plain_answer', models.TextField(blank=True, help_text='Plain text concise answer for AI / Rich Snippet extractability')),
                ('category', models.CharField(choices=[('HOTEL_PICKUP', 'Hotel Pickup & Departures'), ('PRICES', 'Pricing & Payments'), ('CHILDREN', 'Children & Families'), ('WEATHER', 'Weather & Lake Conditions'), ('CRESCENT', 'Crescent Island'), ('SAFETY', 'Safety & Gear'), ('BOOKING', 'Booking & Lead Time')], default='HOTEL_PICKUP', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question & Answer',
                'verbose_name_plural': 'Questions & Answers',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_segment', models.CharField(choices=[('HOTEL_GUEST', 'Hotel Guest'), ('COUPLE', 'Couple / Celebration'), ('FAMILY', 'Family with Children'), ('GROUP', 'Group / Corporate Retreat'), ('PHOTOGRAPHER', 'Photographer / Creator')], default='HOTEL_GUEST', max_length=30)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('source', models.CharField(default='Verified Post-Trip Guest', max_length=50)),
                ('trip_date', models.CharField(default='September 2026', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-id'],
            },
        ),
    ]
