# Generated by Django 6.0.1 on 2026-09-27 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('GOOGLE_MAPS', 'Google Business Profile'), ('TRIPADVISOR', 'TripAdvisor'), ('DIRECT', 'Direct Guest Survey')], default='GOOGLE_MAPS', max_length=30)),
                ('rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=48)),
                ('source_url', models.URLField(blank=True, default='https://maps.google.com/?cid=12648759322304975239')),
                ('captured_at', models.DateField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('summary_quote', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Review Snapshot',
                'verbose_name_plural': 'Review Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='captain',
            name='certification_issuer',
            field=models.CharField(blank=True, default='Kenya Maritime Authority', max_length=120),
        ),
        migrations.AddField(
            model_name='captain',
            name='certification_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='captain',
            name='certification_text',
            field=models.CharField(blank=True, default='KMA Licensed Coxswain & Lake Safety Certified', max_length=255),
        ),
        migrations.AddField(
            model_name='captain',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='e.g. Crescent Island Game Sanctuary Tariff Schedule 2026', max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('OFFICIAL_TARIFF', 'Official Tariff Notice'), ('GOVERNMENT', 'Government Agency (KWS / KMA)'), ('FIELD_OBSERVATION', 'Captain Log / Field Observation'), ('HOTEL_CONFIRMATION', 'Hotel Management Written Confirmation'), ('RESEARCH_PAPER', 'Research Publication')], default='OFFICIAL_TARIFF', max_length=30)),
                ('claim_supported', models.CharField(blank=True, help_text='e.g. Adult resident entrance fee is KES 1,100', max_length=255)),
                ('verified_at', models.DateField(default=django.utils.timezone.now)),
                ('display_publicly', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='content.guidearticle')),
            ],
            options={
                'verbose_name': 'Article Source Citation',
                'verbose_name_plural': 'Article Source Citations',
                'ordering': ['article', 'id'],
            },
        ),
    ]
