# Generated by Django 6.0.1 on 2026-01-30 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('seo_title', models.CharField(blank=True, help_text='Overrides default SEO title', max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('highlights', models.TextField(blank=True, help_text='Bullet-style highlights for snippets & schema')),
                ('location', models.CharField(default='Lake Naivasha', max_length=100)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_people', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_indexing', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('number_of_people', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('X', 'Cancelled')], default='P', max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.tour')),
            ],
        ),
    ]
