# Generated by Django 6.0.1 on 2026-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price_per_person',
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='KES', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='visitor_type',
            field=models.CharField(choices=[('RESIDENT', 'Kenyan Resident'), ('INTERNATIONAL', 'International Visitor')], default='RESIDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='price_international',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD for International Visitors', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='price_resident',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in KES for Kenyan Residents', max_digits=10),
            preserve_default=False,
        ),
    ]
