# Generated by Django 6.0.1 on 2026-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_tour_price_per_person_booking_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
