# Generated by Django 6.0.1 on 2026-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_discount_amount_booking_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
