# Generated by Django 6.0.1 on 2026-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/webp/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='webp_mobile',
            field=models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='tour_images/webp/'),
        ),
    ]
