# Generated by Django 6.0.1 on 2026-09-08 09:29

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_hells_gate_boat_combo'),
        ('packages', '0001_initial'),
        ('partners', '0001_initial'),
        ('stays', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=bookings.models.generate_booking_reference, max_length=30, unique=True)),
                ('lead_type', models.CharField(choices=[('BOAT_ONLY', 'Standard Boat Experience'), ('HOTEL_ORIGIN_RIDE', 'Hotel-Origin Boat Departure'), ('ACCOMMODATION', 'Accommodation Enquiry'), ('STAY_AND_RIDE', 'Stay + Ride Package'), ('FULL_DAY_PACKAGE', 'Full Day Lake Itinerary'), ('GROUP_CORPORATE', 'Corporate / Group Event'), ('SPECIAL_EVENT', 'Special Celebration / Sunset Charter')], default='BOAT_ONLY', max_length=35)),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('NEEDS_HOTEL_CONFIRMATION', 'Awaiting Hotel Clearance / Positioning Confirmation'), ('NEEDS_ACCOMMODATION_CONFIRMATION', 'Awaiting Room Rate / Availability Confirmation'), ('QUOTED', 'Quote Sent to Guest'), ('DEPOSIT_PENDING', 'Deposit Pending'), ('CONFIRMED', 'Booking Confirmed'), ('COMPLETED', 'Trip Completed'), ('CANCELLED', 'Cancelled'), ('LOST', 'Lost / Expired')], default='NEW', max_length=35)),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_phone', models.CharField(max_length=50)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(default='Morning (08:30)', max_length=50)),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('is_private_requested', models.BooleanField(default=False)),
                ('custom_hotel_name', models.CharField(blank=True, help_text='Hotel name if not in partner list', max_length=200)),
                ('room_preference', models.CharField(blank=True, max_length=150)),
                ('transport_required', models.CharField(choices=[('NONE', 'No Road Transport (Self-Drive / Own Arrangements)'), ('NAIROBI_TRANSFER', 'Private Nairobi <-> Naivasha Vehicle Transfer'), ('NAIVASHA_LOCAL', 'Naivasha Local Hotel / SGR Station Transfer')], default='NONE', max_length=30)),
                ('special_requests', models.TextField(blank=True)),
                ('quoted_boat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quoted_hotel_logistics_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quoted_accommodation_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quoted_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('is_accommodation_provisional', models.BooleanField(default=False)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('consent_operational', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal operations notes (never visible to guest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='stays.accommodationproperty')),
                ('hotel_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='partners.hotelpartner')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='packages.package')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='partners.hotelservicepoint')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Booking Lead',
                'verbose_name_plural': 'Booking Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
