# Generated by Django 6.0.1 on 2026-01-30 15:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('plain_answer', models.TextField(blank=True, help_text='Plain text answer for meta description, schema & screen readers')),
                ('answer', tinymce.models.HTMLField()),
                ('seo_title', models.CharField(blank=True, help_text='Overrides default SEO title if provided', max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('search_intent', models.CharField(blank=True, help_text='e.g. pricing, safety, booking, location', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_indexing', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LocalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('seo_title', models.CharField(blank=True, help_text='Used for <title>. Defaults to title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('primary_keyword', models.CharField(help_text="Main keyword e.g. 'Boat rides in Naivasha'", max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. Naivasha, Lake Naivasha, Crescent Island', max_length=100)),
                ('modifiers', models.CharField(blank=True, help_text='Comma-separated: price, safety, sunset, group, birthday', max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('is_active', models.BooleanField(default=True)),
                ('allow_indexing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
