# Generated by Django 6.0.1 on 2026-02-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_localpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='The exact phrase to turn into a link (case-insensitive)', max_length=100, unique=True)),
                ('url', models.CharField(help_text='Relative (e.g. /tours/) or absolute URL', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
    ]
