# Generated by Django 6.0.1 on 2026-02-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_internallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localpage',
            options={'ordering': ['title'], 'verbose_name': 'SEO Local Page', 'verbose_name_plural': 'SEO Local Pages'},
        ),
        migrations.CreateModel(
            name='LocalPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('local_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='seo.localpage')),
            ],
            options={
                'verbose_name': 'Location Image',
                'verbose_name_plural': 'Location Images',
                'ordering': ['order'],
            },
        ),
    ]
