# Generated by Django 6.0.1 on 2026-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_alter_localpage_options_localpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpage',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/webp/'),
        ),
        migrations.AddField(
            model_name='localpage',
            name='webp_mobile',
            field=models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='location_images/webp/'),
        ),
        migrations.AddField(
            model_name='localpageimage',
            name='webp_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_gallery/webp/'),
        ),
        migrations.AddField(
            model_name='localpageimage',
            name='webp_mobile',
            field=models.ImageField(blank=True, help_text='480px width optimized', null=True, upload_to='location_gallery/webp/'),
        ),
        migrations.AlterField(
            model_name='localpage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Used for the browser title tag. Defaults to title.', max_length=70),
        ),
    ]
