# Generated by Django 6.0.1 on 2026-09-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_localpage_webp_image_localpage_webp_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Leading slash path, e.g. /old-boat-ride/', max_length=255, unique=True)),
                ('new_path', models.CharField(help_text='Target path or absolute URL, e.g. /boat-rides/classic-lake-safari/', max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SEO Redirect',
                'verbose_name_plural': 'SEO Redirects',
                'ordering': ['old_path'],
            },
        ),
    ]
